// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: translation.proto

package translation

import (
	com_fs_email_template_model "github.com/sologenic/com-fs-email-template-model"
	formats "github.com/sologenic/com-fs-notification-model/formats"
	parameters "github.com/sologenic/com-fs-notification-model/parameters"
	types "github.com/sologenic/com-fs-notification-model/types"
	language "github.com/sologenic/com-fs-utils-lib/models/language"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationTranslationRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Language         *language.Language      `protobuf:"bytes,1,opt,name=Language,proto3" json:"Language,omitempty"`
	NotificationType types.NotificationType  `protobuf:"varint,2,opt,name=NotificationType,proto3,enum=notification.types.NotificationType" json:"NotificationType,omitempty"`
	Parameter        []*parameters.Parameter `protobuf:"bytes,3,rep,name=Parameter,proto3" json:"Parameter,omitempty"`
	Format           formats.Format          `protobuf:"varint,4,opt,name=Format,proto3,enum=notification.formats.Format" json:"Format,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationTranslationRequest) Reset() {
	*x = NotificationTranslationRequest{}
	mi := &file_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTranslationRequest) ProtoMessage() {}

func (x *NotificationTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTranslationRequest.ProtoReflect.Descriptor instead.
func (*NotificationTranslationRequest) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationTranslationRequest) GetLanguage() *language.Language {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *NotificationTranslationRequest) GetNotificationType() types.NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return types.NotificationType(0)
}

func (x *NotificationTranslationRequest) GetParameter() []*parameters.Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *NotificationTranslationRequest) GetFormat() formats.Format {
	if x != nil {
		return x.Format
	}
	return formats.Format(0)
}

type NotificationTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTranslationResponse) Reset() {
	*x = NotificationTranslationResponse{}
	mi := &file_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTranslationResponse) ProtoMessage() {}

func (x *NotificationTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTranslationResponse.ProtoReflect.Descriptor instead.
func (*NotificationTranslationResponse) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationTranslationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmailTranslationRequest struct {
	state             protoimpl.MessageState                        `protogen:"open.v1"`
	LanguageCode      language.Lang                                 `protobuf:"varint,1,opt,name=LanguageCode,proto3,enum=language.Lang" json:"LanguageCode,omitempty"` // Internal language enum, refer to `language.proto` in `com-fs-utils-lib/models/language`
	EmailTemplateType com_fs_email_template_model.EmailTemplateType `protobuf:"varint,2,opt,name=EmailTemplateType,proto3,enum=emailtemplate.EmailTemplateType" json:"EmailTemplateType,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailTranslationRequest) Reset() {
	*x = EmailTranslationRequest{}
	mi := &file_translation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTranslationRequest) ProtoMessage() {}

func (x *EmailTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTranslationRequest.ProtoReflect.Descriptor instead.
func (*EmailTranslationRequest) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{2}
}

func (x *EmailTranslationRequest) GetLanguageCode() language.Lang {
	if x != nil {
		return x.LanguageCode
	}
	return language.Lang(0)
}

func (x *EmailTranslationRequest) GetEmailTemplateType() com_fs_email_template_model.EmailTemplateType {
	if x != nil {
		return x.EmailTemplateType
	}
	return com_fs_email_template_model.EmailTemplateType(0)
}

type EmailTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailTranslationResponse) Reset() {
	*x = EmailTranslationResponse{}
	mi := &file_translation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailTranslationResponse) ProtoMessage() {}

func (x *EmailTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailTranslationResponse.ProtoReflect.Descriptor instead.
func (*EmailTranslationResponse) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{3}
}

func (x *EmailTranslationResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailTranslationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// Simple text translation
type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Language      language.Lang          `protobuf:"varint,2,opt,name=Language,proto3,enum=language.Lang" json:"Language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{4}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetLanguage() language.Lang {
	if x != nil {
		return x.Language
	}
	return language.Lang(0)
}

type TranslateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslatedText string                 `protobuf:"bytes,1,opt,name=TranslatedText,proto3" json:"TranslatedText,omitempty"`
	TargetLanguage language.Lang          `protobuf:"varint,2,opt,name=TargetLanguage,proto3,enum=language.Lang" json:"TargetLanguage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_translation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{5}
}

func (x *TranslateResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *TranslateResponse) GetTargetLanguage() language.Lang {
	if x != nil {
		return x.TargetLanguage
	}
	return language.Lang(0)
}

var File_translation_proto protoreflect.FileDescriptor

const file_translation_proto_rawDesc = "" +
	"\n" +
	"\x11translation.proto\x12\vtranslation\x1a5sologenic/com-fs-notification-model/types/types.proto\x1a?sologenic/com-fs-notification-model/parameters/parameters.proto\x1a9sologenic/com-fs-notification-model/formats/formats.proto\x1a9sologenic/com-fs-email-template-model/emailtemplate.proto\x1a9sologenic/com-fs-utils-lib/models/language/language.proto\"\x9a\x02\n" +
	"\x1eNotificationTranslationRequest\x12.\n" +
	"\bLanguage\x18\x01 \x01(\v2\x12.language.LanguageR\bLanguage\x12P\n" +
	"\x10NotificationType\x18\x02 \x01(\x0e2$.notification.types.NotificationTypeR\x10NotificationType\x12@\n" +
	"\tParameter\x18\x03 \x03(\v2\".notification.parameters.ParameterR\tParameter\x124\n" +
	"\x06Format\x18\x04 \x01(\x0e2\x1c.notification.formats.FormatR\x06Format\"5\n" +
	"\x1fNotificationTranslationResponse\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\"\x9d\x01\n" +
	"\x17EmailTranslationRequest\x122\n" +
	"\fLanguageCode\x18\x01 \x01(\x0e2\x0e.language.LangR\fLanguageCode\x12N\n" +
	"\x11EmailTemplateType\x18\x02 \x01(\x0e2 .emailtemplate.EmailTemplateTypeR\x11EmailTemplateType\"H\n" +
	"\x18EmailTranslationResponse\x12\x18\n" +
	"\aSubject\x18\x01 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\tR\x04Body\"R\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12*\n" +
	"\bLanguage\x18\x02 \x01(\x0e2\x0e.language.LangR\bLanguage\"s\n" +
	"\x11TranslateResponse\x12&\n" +
	"\x0eTranslatedText\x18\x01 \x01(\tR\x0eTranslatedText\x126\n" +
	"\x0eTargetLanguage\x18\x02 \x01(\x0e2\x0e.language.LangR\x0eTargetLanguage2\xa5\x02\n" +
	"\x12TranslationService\x12d\n" +
	"\x05Parse\x12+.translation.NotificationTranslationRequest\x1a,.translation.NotificationTranslationResponse\"\x00\x12[\n" +
	"\n" +
	"ParseEmail\x12$.translation.EmailTranslationRequest\x1a%.translation.EmailTranslationResponse\"\x00\x12L\n" +
	"\tTranslate\x12\x1d.translation.TranslateRequest\x1a\x1e.translation.TranslateResponse\"\x00B\x0fZ\r./translationb\x06proto3"

var (
	file_translation_proto_rawDescOnce sync.Once
	file_translation_proto_rawDescData []byte
)

func file_translation_proto_rawDescGZIP() []byte {
	file_translation_proto_rawDescOnce.Do(func() {
		file_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translation_proto_rawDesc), len(file_translation_proto_rawDesc)))
	})
	return file_translation_proto_rawDescData
}

var file_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_translation_proto_goTypes = []any{
	(*NotificationTranslationRequest)(nil),             // 0: translation.NotificationTranslationRequest
	(*NotificationTranslationResponse)(nil),            // 1: translation.NotificationTranslationResponse
	(*EmailTranslationRequest)(nil),                    // 2: translation.EmailTranslationRequest
	(*EmailTranslationResponse)(nil),                   // 3: translation.EmailTranslationResponse
	(*TranslateRequest)(nil),                           // 4: translation.TranslateRequest
	(*TranslateResponse)(nil),                          // 5: translation.TranslateResponse
	(*language.Language)(nil),                          // 6: language.Language
	(types.NotificationType)(0),                        // 7: notification.types.NotificationType
	(*parameters.Parameter)(nil),                       // 8: notification.parameters.Parameter
	(formats.Format)(0),                                // 9: notification.formats.Format
	(language.Lang)(0),                                 // 10: language.Lang
	(com_fs_email_template_model.EmailTemplateType)(0), // 11: emailtemplate.EmailTemplateType
}
var file_translation_proto_depIdxs = []int32{
	6,  // 0: translation.NotificationTranslationRequest.Language:type_name -> language.Language
	7,  // 1: translation.NotificationTranslationRequest.NotificationType:type_name -> notification.types.NotificationType
	8,  // 2: translation.NotificationTranslationRequest.Parameter:type_name -> notification.parameters.Parameter
	9,  // 3: translation.NotificationTranslationRequest.Format:type_name -> notification.formats.Format
	10, // 4: translation.EmailTranslationRequest.LanguageCode:type_name -> language.Lang
	11, // 5: translation.EmailTranslationRequest.EmailTemplateType:type_name -> emailtemplate.EmailTemplateType
	10, // 6: translation.TranslateRequest.Language:type_name -> language.Lang
	10, // 7: translation.TranslateResponse.TargetLanguage:type_name -> language.Lang
	0,  // 8: translation.TranslationService.Parse:input_type -> translation.NotificationTranslationRequest
	2,  // 9: translation.TranslationService.ParseEmail:input_type -> translation.EmailTranslationRequest
	4,  // 10: translation.TranslationService.Translate:input_type -> translation.TranslateRequest
	1,  // 11: translation.TranslationService.Parse:output_type -> translation.NotificationTranslationResponse
	3,  // 12: translation.TranslationService.ParseEmail:output_type -> translation.EmailTranslationResponse
	5,  // 13: translation.TranslationService.Translate:output_type -> translation.TranslateResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_translation_proto_init() }
func file_translation_proto_init() {
	if File_translation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translation_proto_rawDesc), len(file_translation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translation_proto_goTypes,
		DependencyIndexes: file_translation_proto_depIdxs,
		MessageInfos:      file_translation_proto_msgTypes,
	}.Build()
	File_translation_proto = out.File
	file_translation_proto_goTypes = nil
	file_translation_proto_depIdxs = nil
}
