// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.1
// source: translation.proto

package translation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TranslationService_Parse_FullMethodName      = "/translation.TranslationService/Parse"
	TranslationService_ParseEmail_FullMethodName = "/translation.TranslationService/ParseEmail"
)

// TranslationServiceClient is the client API for TranslationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationServiceClient interface {
	// Retrieval
	Parse(ctx context.Context, in *NotificationTranslationRequest, opts ...grpc.CallOption) (*NotificationTranslationResponse, error)
	ParseEmail(ctx context.Context, in *EmailTranslationRequest, opts ...grpc.CallOption) (*EmailTranslationResponse, error)
}

type translationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationServiceClient(cc grpc.ClientConnInterface) TranslationServiceClient {
	return &translationServiceClient{cc}
}

func (c *translationServiceClient) Parse(ctx context.Context, in *NotificationTranslationRequest, opts ...grpc.CallOption) (*NotificationTranslationResponse, error) {
	out := new(NotificationTranslationResponse)
	err := c.cc.Invoke(ctx, TranslationService_Parse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationServiceClient) ParseEmail(ctx context.Context, in *EmailTranslationRequest, opts ...grpc.CallOption) (*EmailTranslationResponse, error) {
	out := new(EmailTranslationResponse)
	err := c.cc.Invoke(ctx, TranslationService_ParseEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslationServiceServer is the server API for TranslationService service.
// All implementations should embed UnimplementedTranslationServiceServer
// for forward compatibility
type TranslationServiceServer interface {
	// Retrieval
	Parse(context.Context, *NotificationTranslationRequest) (*NotificationTranslationResponse, error)
	ParseEmail(context.Context, *EmailTranslationRequest) (*EmailTranslationResponse, error)
}

// UnimplementedTranslationServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTranslationServiceServer struct {
}

func (UnimplementedTranslationServiceServer) Parse(context.Context, *NotificationTranslationRequest) (*NotificationTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedTranslationServiceServer) ParseEmail(context.Context, *EmailTranslationRequest) (*EmailTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseEmail not implemented")
}

// UnsafeTranslationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationServiceServer will
// result in compilation errors.
type UnsafeTranslationServiceServer interface {
	mustEmbedUnimplementedTranslationServiceServer()
}

func RegisterTranslationServiceServer(s grpc.ServiceRegistrar, srv TranslationServiceServer) {
	s.RegisterService(&TranslationService_ServiceDesc, srv)
}

func _TranslationService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).Parse(ctx, req.(*NotificationTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranslationService_ParseEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationServiceServer).ParseEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranslationService_ParseEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationServiceServer).ParseEmail(ctx, req.(*EmailTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranslationService_ServiceDesc is the grpc.ServiceDesc for TranslationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translation.TranslationService",
	HandlerType: (*TranslationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _TranslationService_Parse_Handler,
		},
		{
			MethodName: "ParseEmail",
			Handler:    _TranslationService_ParseEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "translation.proto",
}
